### PR TITLE
Fixed compilation errors with newer dependencies

### PR DESCRIPTION
**Pull request by boenrobot**
Locked the TS version to 3.5, as typeorm can't compile on 3.6 yet.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -170,44 +178,64 @@ function GetUtilParametersByArgs() {
...
     connectionOptions.timeout = argv.timeout;
     connectionOptions.user = argv.u ? argv.u.toString() : standardUser;
     const generationOptions: IGenerationOptions = new IGenerationOptions();
     generationOptions.activeRecord = argv.a;
     generationOptions.generateConstructor = argv.generateConstructor;
-    generationOptions.convertCaseEntity = argv.ce;
-    generationOptions.convertCaseFile = argv.cf;
-    generationOptions.convertCaseProperty = argv.cp;
+    generationOptions.convertCaseEntity =
+        argv.ce === "pascal" || argv.ce === "camel" || argv.ce === "none"
```
[the remark this answers is not in the document]
Comment (boenrobot) [reply src/index.ts]: Not in recent versions it seems.

I mean, if you just install the latest versions (ignoring lock files; just honoring package.json), you get "string | number" unless you specifically specify the type. You can only specify "string" or "number" in the type option... and then even if you have choices, you get a "string" in the end.

So at that point, you get a "string is not assignable to {enumValues}" errors. Exhaustively checking each option in this way is the only way to narrow the type. I tried to have an array with indexOf check, but TS is not happy with that.

[the remark this answers is not in the document]
Comment (boenrobot) [reply src/index.ts]: Actually, on recreating the errors from master again...

The cause is yarn vs. npm... I get the following output:
```C:\Projects\github\typeorm-model-generator>yarn install
yarn install v1.17.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. I
t is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynch
ronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning @types/handlebars@4.1.0: This is a stub types definition. handlebars provides its own type defi
nitions, so you do not need this installed.
warning @types/yn@3.1.0: This is a stub types definition. yn provides its own type definitions, so you
do not need this installed.
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ npm run build

> typeorm-model-generator@0.3.5 build C:\Projects\github\typeorm-model-generator
> tsc && ncp src/entity.mst dist/src/entity.mst

src/index.ts:182:9 - error TS2322: Type 'unknown' is not assignable to type 'string'.

182         namingStrategyPath = argv.namingStrategy;
            ~~~~~~~~~~~~~~~~~~

src/index.ts:187:47 - error TS2571: Object is of type 'unknown'.

187     connectionOptions.databaseName = argv.d ? argv.d.toString() : null;
                                                  ~~~~~~

src/index.ts:190:5 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

190     connectionOptions.password = argv.x ? argv.x.toString() : null;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:191:39 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type '
string'.

191     connectionOptions.port = parseInt(argv.p, 10) || standardPort;
                                          ~~~~~~

src/index.ts:192:45 - error TS2571: Object is of type 'unknown'.

192     connectionOptions.schemaName = argv.s ? argv.s.toString() : standardSchema;
                                                ~~~~~~

src/index.ts:195:39 - error TS2571: Object is of type 'unknown'.

195     connectionOptions.user = argv.u ? argv.u.toString() : standardUser;
                                          ~~~~~~

src/index.ts:199:5 - error TS2322: Type 'string' is not assignable to type '"pascal" | "camel" | "none"
'.

199     generationOptions.convertCaseEntity = argv.ce;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:200:5 - error TS2322: Type 'string' is not assignable to type '"pascal" | "param" | "camel
" | "none"'.

200     generationOptions.convertCaseFile = argv.cf;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:201:5 - error TS2322: Type 'string' is not assignable to type '"pascal" | "camel" | "none"
'.

201     generationOptions.convertCaseProperty = argv.cp;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:205:5 - error TS2322: Type 'string' is not assignable to type '"public" | "private" | "non
e" | "protected"'.

205     generationOptions.propertyVisibility = argv.pv;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:208:5 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

208     generationOptions.resultsPath = argv.o ? argv.o.toString() : null;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:209:5 - error TS2322: Type 'string | false' is not assignable to type 'false | "?" | "!"'.
  Type 'string' is not assignable to type 'false | "?" | "!"'.

209     generationOptions.strictMode =
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 12 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! typeorm-model-generator@0.3.5 build: `tsc && ncp src/entity.mst dist/src/entity.mst`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the typeorm-model-generator@0.3.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

File: src/index.ts [hunk 2]
```diff
@@ -170,44 +178,64 @@ function GetUtilParametersByArgs() {
...
     const connectionOptions: IConnectionOptions = new IConnectionOptions();
-    connectionOptions.databaseName = argv.d ? argv.d.toString() : null;
+    connectionOptions.databaseName = argv.d ? argv.d.toString() : "";
     connectionOptions.databaseType = argv.e;
     connectionOptions.host = argv.h;
-    connectionOptions.password = argv.x ? argv.x.toString() : null;
-    connectionOptions.port = parseInt(argv.p, 10) || standardPort;
+    connectionOptions.password = argv.x ? argv.x.toString() : "";
+    connectionOptions.port =
+        typeof argv.p !== "undefined"
```
[the remark this answers is not in the document]
Comment (boenrobot) [reply src/index.ts]: See comment above. It's basically a solution to the TS error above.

File: tsconfig.json [hunk 3]
```diff
@@ -17,10 +17,11 @@
...
         ],
-        "resolveJsonModule": true,
+        "resolveJsonModule": true
     },
     "include": [
         "src",
         "test"
-    ]
+    ],
+    "exclude": ["**/node_modules", "node_modules"]
```
[the remark this answers is not in the document]
Comment (boenrobot) [reply tsconfig.json]: When this package is installed as a dependency with yarn, yarn hoists all dependencies (including this package's depenedncies) into node_modules of the root package, while tsc ignores only dependencies immediately below the tsconfig.json folder. The "**/node_modules" is a way to make it ignore node_modules regardless of whether npm or yarn was used.

File: src/index.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Kononnable) [reply src/index.ts]: Ehh, I hate those yarn vs npm problems :( Npm was a standard once, then yarn came with some improvements that npm was lacking and now we're kind of have two standards which aren't compatible(why? In most cases they could be).
I'll think about what we can do here, in the mean time I guess we have to use npm or manually take care of dependency version -`It is advised not to mix package managers`

[the remark this answers is not in the document]
Comment (boenrobot) [reply src/index.ts]: The full sentence there is "It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files."

In other words, yarn is assuming that if package-lock.json is to be regenerated with npm, you'd still get the same result...

And so I checked... master, with a removed package-lock.json produces the same result... So I've now amended this PR with not only the latest contents of master, but also refreshed depdendencies and a refreshed package-lock.json file.

**Comment by Kononnable** [comment]
Finally got some time to look into the issue.
To make yarn use correct package versions you have to use `yarn import` before installing packages. This will generate `yarn.lock` file based on `package-lock.json`
However later on yarn fails on running `prepare` script(which is required to allow typeorm-model-generator to be installed directly from sources). It looks like yarn is running `prepare` script before all packages are correctly installed in this case.  Which is weird because running yarn without `yarn.lock` works correctly.

To use typeorm-model-generator with yarn you would have to:
- clone the repo
- comment `prepare` script in `package.json`
- `yarn import`
- `yarn install`
- restore `prepare` script
- remove `yarn.lock` file, so it won't be committed

This however won't allow you to install different dependency versions(or you would have to regenerate `package-lock.json` file).

Closing - changes introduced in this PR are already made on next branch.
